/* Everyday Category Match — adaptive difficulty + original project content. */
(function(){
  const rounds=[
    {category:'Kitchen',items:['Steel plate','Cooking spoon','Masala box','Tea cup']},{category:'Bathroom',items:['Soap','Toothbrush','Bath towel','Comb']},{category:'Study Table',items:['Notebook','Pen','Reading glasses','Calendar']},{category:'Bedroom',items:['Pillow','Bedsheet','Shawl','Alarm clock']},{category:'Living Room',items:['Sofa cushion','Newspaper','Remote control','Table lamp']},{category:'Dining Area',items:['Dinner plate','Serving bowl','Water glass','Table mat']},{category:'Cleaning',items:['Broom','Dustpan','Cleaning cloth','Mop']},{category:'Medicine Routine',items:['Medicine box','Pill organizer','Water glass','Reminder card']},{category:'Morning Routine',items:['Toothbrush','Face towel','Comb','Tea cup']},{category:'Cooking',items:['Cooking pot','Spatula','Ladle','Cutting board']},{category:'Reading',items:['Story book','Newspaper','Reading glasses','Bookmark']},{category:'Clothing',items:['Shirt','Socks','Shawl','Clothes hanger']},{category:'Grocery Shopping',items:['Shopping bag','Rice packet','Vegetable basket','Milk packet']},{category:'Garden',items:['Plant pot','Watering can','Garden gloves','Small trowel']},{category:'Going Outside',items:['Walking shoes','Umbrella','Keys','Small bag']}
  ];
  const categories=rounds.map(r=>r.category),difficulty=()=>Math.max(1,Math.min(5,Number(state.level)||1));
  function install(){
    if(typeof state==='undefined'||typeof catalog==='undefined'||typeof $==='undefined'||typeof runGame!=='function'||typeof loadGame!=='function')return false;
    catalog.find={name:'Everyday Category Match',category:'ATTENTION + DAILY-LIFE RECOGNITION',intro:'Look at familiar everyday items and choose the group they belong to.'};
    const oldRunGame=runGame;window.runGame=function(key){if(key==='find')return window.gameCategoryMatch();return oldRunGame(key)};
    window.gameCategoryMatch=function(){const c=state.current;if(!c||c.answered)return;c.categoryRound=0;c.categoryCorrect=0;c.categoryTotal=0;c.categoryConsecutiveMistakes=0;c.categoryMaxRound=rounds.length;c.categoryResults=[];runCategoryRound()};
    function runCategoryRound(){
      const c=state.current;if(!c||c.answered)return;c.categoryRound++;if(c.categoryRound>c.categoryMaxRound){completeCategory();return}
      const base=rounds[c.categoryRound-1],level=difficulty(),itemCount=level<=2?3:4,distractorCount=level<=2?2:level===3?3:4,distractors=shuffle(categories.filter(x=>x!==base.category)).slice(0,distractorCount),choices=shuffle([base.category,...distractors]);
      c.categoryExpected=base.category;c.categoryItems=shuffle(base.items).slice(0,itemCount);c.categoryLocked=false;c.categoryDifficulty=level;
      $('#gamePrompt').textContent='What do these familiar things have in common?';$('#gameArea').innerHTML=`<div class="category-stage category-transition"><div class="category-meta"><span class="category-chip">Question <strong>${c.categoryRound} / ${c.categoryMaxRound}</strong></span><span class="category-chip">Level <strong>${level}</strong></span><span class="category-chip">Score <strong>${c.categoryCorrect}</strong></span><span class="category-chip">Mistakes <strong>${c.categoryConsecutiveMistakes} / 3</strong></span></div><div class="category-progress-line"><span style="width:${(c.categoryRound-1)/c.categoryMaxRound*100}%"></span></div><div class="category-instruction">Which group do these things belong to?</div><div class="category-items">${c.categoryItems.map((item,i)=>`<div class="category-item" style="--delay:${i*55}ms">${item}</div>`).join('')}</div><div class="category-options" aria-label="Choose a category">${choices.map((cat,i)=>`<button class="category-option" type="button" data-category="${cat}">${cat}</button>`).join('')}</div><div class="category-feedback" id="categoryFeedback"></div><div class="category-progress" id="categoryProgress">${c.categoryRound} of ${c.categoryMaxRound}</div></div>`;
      say(level>=4?'Look carefully. There are more choices this time.':'Look at the items carefully. Which group do they belong to?','happy','curious');$$('.category-option').forEach(btn=>btn.addEventListener('click',()=>answerCategory(btn.dataset.category)));
    }
    function answerCategory(answer){const c=state.current;if(!c||c.categoryLocked)return;c.categoryLocked=true;c.categoryTotal++;const ok=answer===c.categoryExpected,fb=$('#categoryFeedback');if(ok){c.categoryCorrect++;c.categoryConsecutiveMistakes=0;fb.textContent='Correct! Nice connection. Moving to the next one.';fb.className='category-feedback correct';setMood('celebrate','happy');setStatus('Correct! Next one.');$$('.category-option').forEach(b=>b.classList.toggle('correct',b.dataset.category===answer))}else{c.categoryConsecutiveMistakes++;fb.textContent=c.categoryConsecutiveMistakes>=3?'Three misses in a row — that is okay. Moving to the next game.':'Not quite. That is okay — moving to the next one.';fb.className='category-feedback incorrect';setMood('encourage','encouraging');setStatus(c.categoryConsecutiveMistakes>=3?'Three misses in a row — moving on.':'Not quite. Next one.');$$('.category-option').forEach(b=>{if(b.dataset.category===answer)b.classList.add('wrong');if(b.dataset.category===c.categoryExpected)b.classList.add('correct')})}setTimeout(()=>{if(c.categoryConsecutiveMistakes>=3)completeCategory();else runCategoryRound()},850)}
    function completeCategory(){const c=state.current;if(!c||c.categoryCompleted)return;c.categoryCompleted=true;c.answered=true;const total=Math.max(1,c.categoryTotal||1),score=Math.round((c.categoryCorrect/total)*100);c.correct=score>=50?1:0;c.score=score;c.seconds=(performance.now()-c.started)/1000;state.results.push({...c,name:catalog.find.name,skipped:false,rounds:c.categoryTotal,correctItems:c.categoryCorrect,totalItems:total,consecutiveMistakes:c.categoryConsecutiveMistakes||0,difficulty:c.categoryDifficulty||state.level});if(window.CognitiveCareCompanion)window.CognitiveCareCompanion.onGameEvent({type:c.correct?'correct':'incorrect'});setStatus('Game complete. Moving to the next game.');setMood(score>=50?'celebrate':'encourage',score>=50?'happy':'encouraging');setTimeout(()=>{if(state.index<4){state.index++;loadGame()}else finishSession()},800)}
    return true;
  }
  if(!install()){const timer=setInterval(()=>{if(install())clearInterval(timer)},50);setTimeout(()=>clearInterval(timer),10000)}
})();