/* Cognitive Care NER — Level 4: guided game mode + Momo wake help + safe exit */
(() => {
  'use strict';
  if (window.__CCNER_LEVEL4__) return;
  window.__CCNER_LEVEL4__ = true;

  const $ = s => document.querySelector(s);
  const LANG = () => localStorage.getItem('ccner-p1-language') || 'en-IN';
  const langKey = () => LANG().slice(0,2);
  const COPY = {
    en:{yes:'Yes',no:'No',ask:'Would you like a tutorial?',title:'Before we play',close:'Continue',exit:'Exit Game',exitTitle:'Leave this game?',exitText:'Your current game will end safely. Any completed games already saved remain available.',stay:'Stay',leave:'Exit Game',wake:'Say “Momo” if you need help.',help:'Here is the game overview again. I will stay quiet while you play.',objective:'Objective',rules:'Rules',interaction:'How to interact'},
    hi:{yes:'हाँ',no:'नहीं',ask:'क्या आप ट्यूटोरियल चाहते हैं?',title:'खेल शुरू करने से पहले',close:'जारी रखें',exit:'गेम से बाहर निकलें',exitTitle:'क्या आप गेम छोड़ना चाहते हैं?',exitText:'आपका वर्तमान गेम सुरक्षित रूप से समाप्त हो जाएगा। पूरे किए गए गेम सेव रहेंगे।',stay:'रुकें',leave:'बाहर निकलें',wake:'मदद चाहिए तो “Momo” बोलें।',help:'यह गेम फिर से समझाता हूँ। खेलते समय मैं शांत रहूँगा।',objective:'उद्देश्य',rules:'नियम',interaction:'कैसे खेलें'},
    bn:{yes:'হ্যাঁ',no:'না',ask:'আপনি কি টিউটোরিয়াল চান?',title:'খেলা শুরুর আগে',close:'চালিয়ে যান',exit:'গেম ছাড়ুন',exitTitle:'গেম ছেড়ে যাবেন?',exitText:'বর্তমান গেমটি নিরাপদে শেষ হবে। সম্পূর্ণ করা গেমগুলো সংরক্ষিত থাকিবে।',stay:'থাকুন',leave:'বেরিয়ে যান',wake:'সাহায্য চাইলে “Momo” বলুন।',help:'গেমটি আবার বুঝিয়ে দিচ্ছি। খেলার সময় আমি চুপ থাকব।',objective:'উদ্দেশ্য',rules:'নিয়ম',interaction:'কীভাবে খেলবেন'},
    as:{yes:'হয়',no:'নহয়',ask:'আপুনি টিউটোৰিয়েল বিচাৰে নেকি?',title:'খেল আৰম্ভ কৰাৰ আগতে',close:'আগবাঢ়ক',exit:'খেল এৰক',exitTitle:'খেল এৰিব নেকি?',exitText:'বৰ্তমান খেলখন সুৰক্ষিতভাৱে শেষ হ’ব। সম্পূৰ্ণ কৰা খেলসমূহ সংৰক্ষিত থাকিব।',stay:'থাকক',leave:'এৰক',wake:'সহায় লাগিলে “Momo” কওক।',help:'খেলখন আকৌ বুজাই দিছোঁ। খেলি থাকোঁতে মই মনে মনে থাকিম।',objective:'উদ্দেশ্য',rules:'নিয়ম',interaction:'কেনেকৈ খেলিব'}
  };
  const t = k => (COPY[langKey()] || COPY.en)[k];

  const gameInfo = {
    'Sequence Memory':{o:{en:'Remember the order in which the colours light up.',hi:'रंग जिस क्रम में जलें, उस क्रम को याद रखें।',bn:'রঙগুলো যে ক্রমে জ্বলে ওঠে, সেই ক্রম মনে রাখুন।',as:'ৰঙবোৰ যি ক্ৰমত জ্বলি উঠে সেই ক্ৰম মনত ৰাখক।'},r:{en:'Watch the colour tiles carefully. After the preview, tap the same colours in the same order.',hi:'रंगों की टाइल ध्यान से देखें। फिर वही रंग उसी क्रम में दबाएँ।',bn:'রঙের টাইলগুলো মন দিয়ে দেখুন। তারপর একই ক্রমে একই রঙ চাপুন।',as:'ৰঙৰ টাইলবোৰ ভালদৰে চাওক। তাৰ পিছত একে ক্ৰমত একে ৰং টিপক।'},i:{en:'Tap one large colour tile at a time. If you need help, say Momo.',hi:'एक-एक करके बड़े रंग के बटन दबाएँ। मदद चाहिए तो Momo बोलें।',bn:'একবারে একটি বড় রঙের টাইল চাপুন। সাহায্য চাইলে Momo বলুন।',as:'এবাৰত এটা ডাঙৰ ৰঙৰ টাইল টিপক। সহায় লাগিলে Momo কওক।'}},
    'Stroop Test':{o:{en:'Choose the colour of the ink, not the word.',hi:'शब्द नहीं, स्याही का रंग चुनें।',bn:'শব্দ নয়, লেখার কালি যে রঙে আছে সেই রঙ বেছে নিন।',as:'শব্দটো নহয়, লিখনিটো যি ৰঙৰ সেই ৰংটো বাছক।'},r:{en:'A colour word will appear in a possibly different ink colour. Select the ink colour. Keep going for two minutes.',hi:'एक रंग का शब्द दूसरे रंग की स्याही में आ सकता है। स्याही का रंग चुनें और दो मिनट तक जारी रखें।',bn:'একটি রঙের শব্দ অন্য রঙের কালিতে দেখা যেতে পারে। কালির রঙ বেছে নিয়ে দুই মিনিট চালিয়ে যান।',as:'এটা ৰঙৰ শব্দ আন এটা ৰঙৰ কালিত দেখা দিব পাৰে। কালিৰ ৰংটো বাছি দুই মিনিট খেলক।'},i:{en:'Tap the large colour answer. Accuracy comes first; speed is adjusted gradually.',hi:'बड़ा रंग वाला उत्तर दबाएँ। पहले सही होना ज़रूरी है; गति धीरे-धीरे बढ़ेगी।',bn:'বড় রঙের উত্তরটি চাপুন। আগে সঠিকতা; গতি ধীরে ধীরে বাড়বে।',as:'ডাঙৰ ৰঙৰ উত্তৰটো টিপক। প্ৰথমে শুদ্ধতা; গতি লাহে লাহে বাঢ়িব।'}},
    'Around the House Sorting':{o:{en:'Put each familiar household item in the place where it belongs.',hi:'हर परिचित घरेलू वस्तु को सही जगह पर रखें।',bn:'প্রতিটি পরিচিত ঘরের জিনিস তার সঠিক জায়গায় রাখুন।',as:'প্ৰতিটো চিনাকি ঘৰুৱা বস্তু তাৰ সঠিক ঠাইত ৰাখক।'},r:{en:'Look at every item, choose one of the two locations, then press Check Answers.',hi:'हर वस्तु देखें, दो जगहों में से एक चुनें, फिर उत्तर जाँचें।',bn:'প্রতিটি জিনিস দেখুন, দুটি জায়গার একটি বেছে নিন, তারপর উত্তর পরীক্ষা করুন।',as:'প্ৰতিটো বস্তু চাওক, দুটা ঠাইৰ এটাৰ বাছনি কৰক, তাৰ পিছত উত্তৰ পৰীক্ষা কৰক।'},i:{en:'Tap the large location button for each row. You can change an answer before checking.',hi:'हर पंक्ति में बड़ा जगह वाला बटन दबाएँ। जाँचने से पहले उत्तर बदल सकते हैं।',bn:'প্রতিটি সারিতে বড় জায়গার বোতাম চাপুন। পরীক্ষা করার আগে উত্তর বদলাতে পারবেন।',as:'প্ৰতিটো শাৰীত ডাঙৰ ঠাইৰ বুটাম টিপক। পৰীক্ষাৰ আগতে উত্তৰ সলাব পাৰে।'}},
    'Pattern Recognition':{o:{en:'Find the rule in the sequence and choose what comes next.',hi:'क्रम में नियम पहचानें और अगला अंक चुनें।',bn:'ধারার নিয়ম খুঁজে পরের সংখ্যাটি বেছে নিন।',as:'ধাৰাটোৰ নিয়ম বিচাৰি পৰৱৰ্তী সংখ্যাটো বাছক।'},r:{en:'Look carefully at the sequence, think about how it changes, then choose one large answer.',hi:'क्रम को ध्यान से देखें, बदलाव समझें और एक बड़ा उत्तर चुनें।',bn:'ধারাটি মন দিয়ে দেখুন, কীভাবে বদলাচ্ছে বুঝুন, তারপর একটি বড় উত্তর বেছে নিন।',as:'ধাৰাটো ভালদৰে চাওক, কেনেকৈ সলনি হৈছে বুজক আৰু এটা ডাঙৰ উত্তৰ বাছক।'},i:{en:'Tap one answer. Afterward Momo may explain the rule so you can learn the pattern.',hi:'एक उत्तर दबाएँ। बाद में Momo नियम समझा सकता है ताकि आप पैटर्न सीख सकें।',bn:'একটি উত্তর চাপুন। পরে Momo নিয়মটি বোঝাতে পারে যাতে আপনি ধারাটি শিখতে পারেন।',as:'এটা উত্তৰ টিপক। পিছত Momo-এ নিয়মটো বুজাই দিব পাৰে যাতে আপুনি আৰ্হিটো শিকিব পাৰে।'}},
    'Spot the Difference':{o:{en:'Remember the items, then find the item that changed.',hi:'वस्तुओं को याद रखें, फिर बदली हुई वस्तु खोजें।',bn:'জিনিসগুলো মনে রাখুন, তারপর যে জিনিসটি বদলেছে সেটি খুঁজুন।',as:'বস্তুবোৰ মনত ৰাখক, তাৰ পিছত সলনি হোৱা বস্তুটো বিচাৰক।'},r:{en:'First you get a short memorization phase. Then the same set returns with one item changed. Tap the changed item.',hi:'पहले थोड़ी देर याद करने का समय मिलेगा। फिर एक वस्तु बदली हुई दिखाई देगी। बदली वस्तु दबाएँ।',bn:'প্রথমে অল্প সময় মনে রাখার জন্য দেখানো হবে। তারপর একটি জিনিস বদলে যাবে। বদলানো জিনিসটি চাপুন।',as:'প্ৰথমে অলপ সময় মনত ৰখাৰ বাবে দেখুওৱা হ’ব। তাৰ পিছত এটা বস্তু সলনি হ’ব। সলনি হোৱা বস্তুটো টিপক।'},i:{en:'Tap the large item that was not in the original set. If you need help, say Momo.',hi:'बड़ी उस वस्तु को दबाएँ जो पहले नहीं थी। मदद चाहिए तो Momo बोलें।',bn:'যে বড় জিনিসটি আগে ছিল না সেটি চাপুন। সাহায্য চাইলে Momo বলুন।',as:'আগতে নথকা ডাঙৰ বস্তুটো টিপক। সহায় লাগিলে Momo কওক।'}}
  };

  let gateOpen=false,pendingTimers=[],observer,recognition,recognitionRunning=false;
  const nativeSetTimeout=window.setTimeout.bind(window);
  window.setTimeout=function(fn,ms,...args){const src=typeof fn==='function'?Function.prototype.toString.call(fn):'';if(!gateOpen&&typeof fn==='function'&&/beginRound/.test(src)&&Number(ms)<=2000){pendingTimers.push(()=>fn(...args));return -1}return nativeSetTimeout(fn,ms,...args)};
  function speak(text){try{if('speechSynthesis'in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=LANG();u.rate=.9;u.pitch=1.08;speechSynthesis.speak(u)}}catch(_){}
  }
  function currentInfo(){const title=$('#gameTitle')?.textContent?.trim()||'';return gameInfo[title]||null}
  function modal(html,cls='l4-modal'){document.querySelector('.'+cls)?.remove();const wrap=document.createElement('div');wrap.className=cls;wrap.innerHTML=html;document.body.appendChild(wrap);return wrap}
  function tutorial(){const info=currentInfo();if(!info){openGate();return}const k=langKey(),get=x=>x[k]||x.en;const el=modal(`<div class="l4-dialog" role="dialog" aria-modal="true"><div class="l4-momo">🐶</div><p class="l4-eyebrow">MOMO</p><h2>${t('title')}</h2><h3>${t('objective')}</h3><p>${get(info.o)}</p><h3>${t('rules')}</h3><p>${get(info.r)}</p><h3>${t('interaction')}</h3><p>${get(info.i)}</p><div class="l4-badges"><span>1 · Look</span><span>2 · Think</span><span>3 · Tap</span></div><p class="l4-quiet">${t('wake')}</p><button id="l4Continue" class="l4-primary">${t('close')}</button></div>`);$('#l4Continue',el)?.addEventListener('click',()=>{el.remove();openGate();speak(t('help'))});speak(`${get(info.o)} ${get(info.r)} ${get(info.i)}`)}
  function askTutorial(){const el=modal(`<div class="l4-dialog l4-ask" role="dialog" aria-modal="true"><div class="l4-momo">🐶</div><p class="l4-eyebrow">MOMO</p><h2>${t('ask')}</h2><div class="l4-choice-row"><button id="l4Yes" class="l4-primary">${t('yes')}</button><button id="l4No" class="l4-secondary">${t('no')}</button></div></div>`);$('#l4Yes',el)?.addEventListener('click',tutorial);$('#l4No',el)?.addEventListener('click',()=>{el.remove();openGate()});speak(t('ask'))}
  function openGate(){gateOpen=true;const q=pendingTimers.splice(0);q.forEach(fn=>nativeSetTimeout(fn,50));setGameChrome();startWake()}
  function setGameChrome(){const game=$('#gameView');if(!game||game.hidden)return;if(!document.getElementById('l4Exit'))game.insertAdjacentHTML('afterbegin',`<div class="l4-gamebar"><span>🐾 ${t('wake')}</span><button id="l4Exit" type="button">${t('exit')}</button></div>`);const exit=$('#l4Exit');if(exit&&!exit.dataset.bound){exit.dataset.bound='1';exit.addEventListener('click',exitConfirm)}const row=$('.chat-row');if(row)row.classList.add('l4-disabled');const input=$('#chatInput');if(input){input.disabled=true;input.placeholder=t('wake')}}
  function exitConfirm(){const el=modal(`<div class="l4-dialog" role="dialog" aria-modal="true"><div class="l4-momo">🐶</div><h2>${t('exitTitle')}</h2><p>${t('exitText')}</p><div class="l4-choice-row"><button id="l4Stay" class="l4-secondary">${t('stay')}</button><button id="l4Leave" class="l4-primary">${t('leave')}</button></div></div>`);$('#l4Stay',el)?.addEventListener('click',()=>el.remove());$('#l4Leave',el)?.addEventListener('click',()=>{el.remove();safeExit()})}
  function safeExit(){gateOpen=true;pendingTimers=[];stopWake();try{speechSynthesis?.cancel()}catch(_){}const game=$('#gameView');if(game)game.hidden=true;const home=$('#homeView');if(home)home.hidden=false;const status=$('#todayStatus');if(status)status.textContent='Session exited';document.querySelector('.l4-gamebar')?.remove();window.dispatchEvent(new CustomEvent('ccner:level4-exit'));speak('Okay. We can try again whenever you are ready.')}
  function startWake(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR||recognitionRunning)return;try{recognition=new SR();recognition.lang=LANG();recognition.continuous=true;recognition.interimResults=false;recognition.onresult=e=>{for(let i=e.resultIndex;i<e.results.length;i++){if(!e.results[i].isFinal)continue;const text=e.results[i][0].transcript.toLowerCase();if(/\bmomo\b/.test(text)){const info=currentInfo();if(info){const k=langKey(),get=x=>x[k]||x.en;speak(`${get(info.o)} ${get(info.r)} ${get(info.i)}`);flashHelp(get(info.r))}}}};recognition.onend=()=>{recognitionRunning=false;if(gateOpen&&$('#gameView')&&!$('#gameView').hidden)nativeSetTimeout(startWake,250)};recognition.onerror=()=>{recognitionRunning=false};recognition.start();recognitionRunning=true}catch(_){recognitionRunning=false}}
  function stopWake(){try{recognition?.stop()}catch(_){}recognitionRunning=false}
  function flashHelp(text){const el=modal(`<div class="l4-help" role="status"><div class="l4-momo">🐶</div><strong>Momo</strong><p>${text}</p></div>`,'l4-help-modal');nativeSetTimeout(()=>el.remove(),3500)}
  const originalStart=window.startSession;
  window.startSession=function(){if(typeof originalStart!=='function')return;gateOpen=false;pendingTimers=[];originalStart();nativeSetTimeout(()=>{setGameChrome();askTutorial()},80)};
  observer=new MutationObserver(()=>{const game=$('#gameView');if(!game||game.hidden)return;setGameChrome();const title=$('#gameTitle')?.textContent?.trim()||'';if(title&&observer._lastTitle!==title){observer._lastTitle=title;if(gateOpen){gateOpen=false;pendingTimers=[];askTutorial()}}});
  observer.observe(document.documentElement,{subtree:true,childList:true,characterData:true});
  document.addEventListener('click',e=>{if(e.target.closest('#l4Exit'))return},true);
})();
