/* Cognitive Care NER — complete regional-language UI, game and voice layer.
 * Supported NER-ready demo locales: English, Hindi, Bengali and Assamese.
 * Core localization is offline/local: no translation service is required.
 */
(() => {
  'use strict';
  const KEY='ccner-language';
  const LANGS={'en-IN':{name:'English',native:'English'},'hi-IN':{name:'Hindi',native:'हिन्दी'},'bn-IN':{name:'Bengali',native:'বাংলা'},'as-IN':{name:'Assamese',native:'অসমীয়া'},'lus-IN':{name:'Mizo',native:'Mizo'},'kha-IN':{name:'Khasi',native:'Khasi'},'mni-IN':{name:'Meitei (Manipuri)',native:'ꯃꯤꯇꯩꯂꯣꯟ'},'njz-IN':{name:'Nyishi',native:'Nyishi'}};
  const T={
    'en-IN':{title:'Meet Mimo',subtitle:"Your playful companion for today's brain workout.",ready:'Ready to play',start:"🎮 Start today's session",talk:'🎙️ Talk to Mimo',reminders:'⏰ Reminders',progress:'📈 Progress',hands:'Hands-free voice',handsText:'Tap Talk once. After Mimo replies, Mimo automatically listens again.',today:'TODAY',routine:'Your little daily routine',activity:"Today's activity",games:'Games',focus:'Focus',promise:"🐾 Mimo's promise",noPressure:'No pressure. Just one small step at a time.',send:'Send',placeholder:'Or type to Mimo…',language:'Language & voice',choose:'Choose your language',saved:'Language saved',safety:'Safety: training scores describe game performance only. They do not diagnose dementia or assign a clinical stage.',session:'SESSION COMPLETE',performance:'TRAINING PERFORMANCE',todaysGames:"Today's games",playAgain:'🔁 Play again',home:'⌂ Home'},
    'hi-IN':{title:'मोमो से मिलिए',subtitle:'आज के दिमागी अभ्यास के लिए आपका प्यारा साथी।',ready:'खेलने के लिए तैयार',start:'🎮 आज का अभ्यास शुरू करें',talk:'🎙️ मोमो से बात करें',reminders:'⏰ रिमाइंडर',progress:'📈 प्रगति',hands:'हैंड्स-फ्री आवाज़',handsText:'एक बार बात करें। मोमो के जवाब के बाद वह फिर से आपकी आवाज़ सुनेगा।',today:'आज',routine:'आपकी छोटी दैनिक दिनचर्या',activity:'आज की गतिविधि',games:'खेल',focus:'ध्यान',promise:'🐾 मोमो का वादा',noPressure:'कोई दबाव नहीं। बस एक छोटा कदम, एक समय में।',send:'भेजें',placeholder:'या मोमो को लिखें…',language:'भाषा और आवाज़',choose:'अपनी भाषा चुनें',saved:'भाषा सेव हो गई',safety:'सुरक्षा: ये स्कोर केवल खेल के प्रदर्शन को बताते हैं। ये डिमेंशिया का निदान या क्लिनिकल स्टेज नहीं बताते।',session:'अभ्यास पूरा',performance:'अभ्यास प्रदर्शन',todaysGames:'आज के खेल',playAgain:'🔁 फिर खेलें',home:'⌂ होम'},
    'bn-IN':{title:'মোমোর সাথে দেখা করুন',subtitle:'আজকের মস্তিষ্কের অনুশীলনের জন্য আপনার মজার সঙ্গী।',ready:'খেলার জন্য প্রস্তুত',start:'🎮 আজকের অনুশীলন শুরু করুন',talk:'🎙️ মোমোর সাথে কথা বলুন',reminders:'⏰ রিমাইন্ডার',progress:'📈 অগ্রগতি',hands:'হ্যান্ডস-ফ্রি ভয়েস',handsText:'একবার Talk চাপুন। মোমো উত্তর দেওয়ার পর আবার আপনার কথা শুনবে।',today:'আজ',routine:'আপনার ছোট দৈনিক রুটিন',activity:'আজকের কাজ',games:'গেম',focus:'মনোযোগ',promise:'🐾 মোমোর প্রতিশ্রুতি',noPressure:'কোনও চাপ নেই। একবারে একটি ছোট পদক্ষেপ।',send:'পাঠান',placeholder:'অথবা মোমোকে লিখুন…',language:'ভাষা ও ভয়েস',choose:'আপনার ভাষা বেছে নিন',saved:'ভাষা সংরক্ষিত হয়েছে',safety:'নিরাপত্তা: এই স্কোর শুধু গেমের পারফরম্যান্স বোঝায়। এটি ডিমেনশিয়ার রোগ নির্ণয় বা ক্লিনিক্যাল স্টেজ নয়।',session:'সেশন সম্পূর্ণ',performance:'অনুশীলনের ফলাফল',todaysGames:'আজকের গেম',playAgain:'🔁 আবার খেলুন',home:'⌂ হোম'},
    'as-IN':{title:'মোমোক লগ পাওক',subtitle:'আজিৰ মগজুৰ অনুশীলনৰ বাবে আপোনাৰ মৰমলগা সংগী।',ready:'খেলিবলৈ সাজু',start:'🎮 আজিৰ অনুশীলন আৰম্ভ কৰক',talk:'🎙️ মোমোৰ সৈতে কথা পাতক',reminders:'⏰ সোঁৱৰনী',progress:'📈 অগ্ৰগতি',hands:'হেণ্ডছ-ফ্ৰী ভইচ',handsText:'এবাৰ Talk টিপক। মোমোৱে উত্তৰ দিয়াৰ পিছত আকৌ আপোনাৰ কথা শুনিব।',today:'আজি',routine:'আপোনাৰ সৰু দৈনিক ৰুটিন',activity:'আজিৰ কাৰ্যকলাপ',games:'খেল',focus:'মনোযোগ',promise:'🐾 মোমোৰ প্ৰতিশ্ৰুতি',noPressure:'কোনো হেঁচা নাই। এটাকৈ সৰু খোজ লওঁ আহক।',send:'পঠাওক',placeholder:'অথবা মোমোক লিখক…',language:'ভাষা আৰু ভইচ',choose:'আপোনাৰ ভাষা বাছক',saved:'ভাষা সংৰক্ষণ কৰা হৈছে',safety:'সুৰক্ষা: এই স্ক’ৰ কেৱল খেলৰ প্ৰদৰ্শন বুজায়। ই ডিমেনচিয়াৰ ৰোগ নিৰ্ণয় বা ক্লিনিকেল ষ্টেজ নহয়।',session:'ছেছন সম্পূৰ্ণ',performance:'অনুশীলনৰ ফলাফল',todaysGames:'আজিৰ খেল',playAgain:'🔁 আকৌ খেলক',home:'⌂ হোম'},
    'lus-IN':{title:'Mimo',subtitle:'Your friendly companion for today\'s brain workout.',ready:'Zuih loh tur',start:'🎮 Tunah session chu tan rawh',talk:'🎙️ Mimo nen inbiak rawh',reminders:'⏰ Hriattirna',progress:'📈 Hmasawnna',hands:'Hands-free voice',handsText:'Tap Talk once. Mimo will listen again after replying.',today:'TUNAH',routine:'I nitin routine te',activity:'Tunah activity',games:'Games',focus:'Focus',promise:'🐾 Mimo\'s promise',noPressure:'Pressure awm lo. Step te te in kal rawh.',send:'Thawn',placeholder:'Mimo hnenah ziak rawh…',language:'Tawng leh aw',choose:'I tawng thlang rawh',saved:'Tawng dah fel a ni',safety:'Safety: training scores describe game performance only.',session:'SESSION COMPLETE',performance:'TRAINING PERFORMANCE',todaysGames:'Tunah games',playAgain:'🔁 Again play',home:'⌂ Home'},
    'kha-IN':{title:'Mimo bad phi',subtitle:'Your friendly companion for today\'s brain workout.',ready:'La pynkhreh ban lehkai',start:'🎮 Sdang ïa ka session mynta',talk:'🎙️ Ïakren bad Mimo',reminders:'⏰ Ki jingpynkynmaw',progress:'📈 Ka jingkiew',hands:'Hands-free voice',handsText:'Tap Talk once. Mimo will listen again after replying.',today:'MYNTA',routine:'Ka routine jong phi',activity:'Ka kam mynta',games:'Ki game',focus:'Ka jingsngewthuh',promise:'🐾 Ka jingkular jong Mimo',noPressure:'Ym don jingpynbor. Kawei ka step ha ka por.',send:'Phah',placeholder:'Ne thoh sha Mimo…',language:'Ka ktien bad ka sur',choose:'Jied ïa ka ktien jong phi',saved:'La buh ïa ka ktien',safety:'Safety: training scores describe game performance only.',session:'LA PYNDAP',performance:'TRAINING PERFORMANCE',todaysGames:'Ki game mynta',playAgain:'🔁 Leh biang',home:'⌂ Home'},
    'mni-IN':{title:'Mimo',subtitle:'Your friendly companion for today\'s brain workout.',ready:'ꯁꯥꯔꯦ',start:'🎮 ꯍꯧꯖꯤꯛ ꯁꯦꯁꯟ ꯍꯧꯗꯣꯛꯎ',talk:'🎙️ ꯃꯣꯃꯣꯒꯥ ꯋꯥꯍꯪꯁꯤ',reminders:'⏰ ꯅꯨꯡꯁꯤꯕ',progress:'📈 ꯆꯠꯂꯤ',hands:'Hands-free voice',handsText:'Tap Talk once. Mimo will listen again after replying.',today:'ꯅꯣꯡꯃꯥ',routine:'ꯅꯍꯥꯛꯀꯤ ꯅꯤꯇꯤꯅ ꯔꯨꯇꯤꯅ',activity:'ꯅꯣꯡꯃꯥꯒꯤ ꯊꯧꯔꯥꯡ',games:'ꯒꯦꯝ',focus:'ꯁꯦꯡꯕ',promise:'🐾 Mimoꯒꯤ ꯁꯥꯅꯥ',noPressure:'ꯄ꯭ꯔꯦꯁꯔ ꯂꯩꯇꯦ। ꯃꯥꯌꯥꯝ ꯑꯃꯒꯤ ꯃꯇꯤꯛ ꯇꯥꯡꯖꯔꯣ.',send:'ꯊꯥꯔꯣ',placeholder:'ꯅꯣꯟꯗ ꯃꯣꯃꯣꯗꯥ ꯂꯤꯕꯥ…',language:'ꯂꯣꯟ ꯑꯃꯁꯨꯡ ꯋꯥꯍꯪ',choose:'ꯅꯍꯥꯛꯀꯤ ꯂꯣꯟ ꯈꯜꯂꯣ',saved:'ꯂꯣꯟ ꯊꯝꯂꯦ',safety:'Safety: training scores describe game performance only.',session:'ꯁꯦꯁꯟ ꯂꯣꯏꯔꯦ',performance:'TRAINING PERFORMANCE',todaysGames:'ꯅꯣꯡꯃꯥꯒꯤ ꯒꯦꯝ',playAgain:'🔁 ꯑꯃꯨꯛ ꯊꯣꯛꯎ',home:'⌂ Home'},
    'njz-IN':{title:'Mimo',subtitle:'Your friendly companion for today\'s brain workout.',ready:'Ready to play',start:'🎮 Start today\'s session',talk:'🎙️ Talk to Mimo',reminders:'⏰ Reminders',progress:'📈 Progress',hands:'Hands-free voice',handsText:'Tap Talk once. Mimo will listen again after replying.',today:'TODAY',routine:'Your little daily routine',activity:'Today\'s activity',games:'Games',focus:'Focus',promise:'🐾 Mimo\'s promise',noPressure:'No pressure. Just one small step at a time.',send:'Send',placeholder:'Or type to Mimo…',language:'Language & voice',choose:'Choose your language',saved:'Language saved',safety:'Safety: training scores describe game performance only.',session:'SESSION COMPLETE',performance:'TRAINING PERFORMANCE',todaysGames:'Today\'s games',playAgain:'🔁 Play again',home:'⌂ Home'}
  };
  const EN={
    'Round':'Round','Level':'Level','Score':'Score','Misses':'Misses','Mistakes':'Mistakes','Question':'Question','Correct':'Correct','Step':'Step','Game complete. Moving to the next game.':'Game complete. Moving to the next game.','Next round.':'Next round.','Next one.':'Next one.','Next pattern.':'Next pattern.','Look carefully…':'Look carefully…','Get ready…':'Get ready…','Your turn':'Your turn','Correct!':'Correct!','Incorrect':'Incorrect','Not quite.':'Not quite.','Memory':'Memory','Attention':'Attention','Pattern Recognition':'Pattern Recognition','Object Recognition':'Object Recognition','Daily Routine Recall':'Daily Routine Recall','MEMORY + ATTENTION':'MEMORY + ATTENTION','ATTENTION + DAILY-LIFE RECOGNITION':'ATTENTION + DAILY-LIFE RECOGNITION','DAILY-LIFE RECOGNITION':'DAILY-LIFE RECOGNITION','PATTERN RECOGNITION':'PATTERN RECOGNITION','OBJECT RECOGNITION + ATTENTION':'OBJECT RECOGNITION + ATTENTION',
    'Kitchen':'Kitchen','Study Table':'Study Table','Bedroom':'Bedroom','Bathroom':'Bathroom','Dining Area':'Dining Area','Living Room':'Living Room','Cleaning':'Cleaning','Medicine Routine':'Medicine Routine','Morning Routine':'Morning Routine','Cooking':'Cooking','Reading':'Reading','Clothing':'Clothing','Grocery Shopping':'Grocery Shopping','Garden':'Garden','Going Outside':'Going Outside','Other place':'Other place',
    'Steel plate':'Steel plate','Cooking spoon':'Cooking spoon','Masala box':'Masala box','Tea cup':'Tea cup','Soap':'Soap','Toothbrush':'Toothbrush','Bath towel':'Bath towel','Comb':'Comb','Notebook':'Notebook','Pen':'Pen','Reading glasses':'Reading glasses','Calendar':'Calendar','Pillow':'Pillow','Bedsheet':'Bedsheet','Shawl':'Shawl','Alarm clock':'Alarm clock','Sofa cushion':'Sofa cushion','Newspaper':'Newspaper','Remote control':'Remote control','Table lamp':'Table lamp','Dinner plate':'Dinner plate','Serving bowl':'Serving bowl','Water glass':'Water glass','Table mat':'Table mat','Broom':'Broom','Dustpan':'Dustpan','Cleaning cloth':'Cleaning cloth','Mop':'Mop','Medicine box':'Medicine box','Pill organizer':'Pill organizer','Reminder card':'Reminder card','Face towel':'Face towel','Cooking pot':'Cooking pot','Spatula':'Spatula','Ladle':'Ladle','Cutting board':'Cutting board','Story book':'Story book','Bookmark':'Bookmark','Shirt':'Shirt','Socks':'Socks','Clothes hanger':'Clothes hanger','Shopping bag':'Shopping bag','Rice packet':'Rice packet','Vegetable basket':'Vegetable basket','Milk packet':'Milk packet','Plant pot':'Plant pot','Watering can':'Watering can','Garden gloves':'Garden gloves','Small trowel':'Small trowel','Walking shoes':'Walking shoes','Umbrella':'Umbrella','Keys':'Keys','Small bag':'Small bag','Steel spoon':'Steel spoon','Masala jar':'Masala jar','Steel tumbler':'Steel tumbler','Bed pillow':'Bed pillow','Body lotion':'Body lotion','Bath bucket':'Bath bucket','Cushion':'Cushion','Rice container':'Rice container','Tea kettle':'Tea kettle','Clothes basket':'Clothes basket','Tawa':'Tawa','Exercise book':'Exercise book','Wall clock':'Wall clock','Pencil':'Pencil','Ruler':'Ruler',
    'Wake up':'Wake up','Brush teeth':'Brush teeth','Wash face':'Wash face','Have tea':'Have tea','Have breakfast':'Have breakfast','Take medicine':'Take medicine','Take a bath':'Take a bath','Get dressed':'Get dressed','Comb hair':'Comb hair','Go outside':'Go outside','Notice the reminder':'Notice the reminder','Drink water':'Drink water','Sit and rest':'Sit and rest','Mark it as done':'Mark it as done','Have dinner':'Have dinner','Take evening medicine':'Take evening medicine','Read a little':'Read a little','Wash up':'Wash up','Go to bed':'Go to bed','Prepare tea':'Prepare tea','Pour tea':'Pour tea','Take a small snack':'Take a small snack','Sit comfortably':'Sit comfortably','Enjoy tea':'Enjoy tea','Get ready':'Get ready','Put on walking shoes':'Put on walking shoes','Take the keys':'Take the keys','Carry water':'Carry water','Go for a walk':'Go for a walk'
  };
  const G={'en-IN':EN,'hi-IN':{},'bn-IN':{},'as-IN':{}};
  Object.assign(G['hi-IN'],{
    'Round':'राउंड','Level':'स्तर','Score':'स्कोर','Misses':'गलतियाँ','Mistakes':'गलतियाँ','Question':'सवाल','Correct':'सही','Step':'कदम','Game complete. Moving to the next game.':'खेल पूरा हुआ। अब अगले खेल पर चलते हैं।','Next round.':'अगला राउंड।','Next one.':'अगला सवाल।','Next pattern.':'अगला पैटर्न।','Look carefully…':'ध्यान से देखें…','Get ready…':'तैयार हो जाइए…','Your turn':'अब आपकी बारी','Correct!':'सही!','Incorrect':'गलत','Not quite.':'पूरी तरह सही नहीं।','Memory':'याददाश्त','Attention':'ध्यान','Pattern Recognition':'पैटर्न पहचान','Object Recognition':'वस्तु पहचान','Daily Routine Recall':'दैनिक दिनचर्या याद करना','MEMORY + ATTENTION':'याददाश्त + ध्यान','ATTENTION + DAILY-LIFE RECOGNITION':'ध्यान + दैनिक जीवन पहचान','DAILY-LIFE RECOGNITION':'दैनिक जीवन पहचान','PATTERN RECOGNITION':'पैटर्न पहचान','OBJECT RECOGNITION + ATTENTION':'वस्तु पहचान + ध्यान',
    'Kitchen':'रसोई','Study Table':'पढ़ने की मेज','Bedroom':'शयनकक्ष','Bathroom':'बाथरूम','Dining Area':'खाने की जगह','Living Room':'बैठक','Cleaning':'सफाई','Medicine Routine':'दवा की दिनचर्या','Morning Routine':'सुबह की दिनचर्या','Cooking':'खाना बनाना','Reading':'पढ़ना','Clothing':'कपड़े','Grocery Shopping':'किराने की खरीदारी','Garden':'बगीचा','Going Outside':'बाहर जाना','Other place':'दूसरी जगह',
    'Steel plate':'स्टील की थाली','Cooking spoon':'खाना पकाने का चम्मच','Masala box':'मसाले का डिब्बा','Tea cup':'चाय का कप','Soap':'साबुन','Toothbrush':'टूथब्रश','Bath towel':'नहाने का तौलिया','Comb':'कंघी','Notebook':'कॉपी','Pen':'कलम','Reading glasses':'पढ़ने का चश्मा','Calendar':'कैलेंडर','Pillow':'तकिया','Bedsheet':'चादर','Shawl':'शॉल','Alarm clock':'अलार्म घड़ी','Sofa cushion':'सोफे का कुशन','Newspaper':'अखबार','Remote control':'रिमोट','Table lamp':'टेबल लैंप','Dinner plate':'खाने की थाली','Serving bowl':'परोसने का कटोरा','Water glass':'पानी का गिलास','Table mat':'टेबल मैट','Broom':'झाड़ू','Dustpan':'कूड़ा-पट्टी','Cleaning cloth':'सफाई का कपड़ा','Mop':'पोछा','Medicine box':'दवा का डिब्बा','Pill organizer':'दवा रखने का डिब्बा','Reminder card':'याद दिलाने का कार्ड','Face towel':'चेहरा पोंछने का तौलिया','Cooking pot':'खाना पकाने का बर्तन','Spatula':'पलटा','Ladle':'कलछी','Cutting board':'काटने का बोर्ड','Story book':'कहानी की किताब','Bookmark':'बुकमार्क','Shirt':'कमीज़','Socks':'मोज़े','Clothes hanger':'कपड़े का हैंगर','Shopping bag':'खरीदारी का बैग','Rice packet':'चावल का पैकेट','Vegetable basket':'सब्ज़ियों की टोकरी','Milk packet':'दूध का पैकेट','Plant pot':'गमला','Watering can':'पानी देने का डिब्बा','Garden gloves':'बगीचे के दस्ताने','Small trowel':'छोटी खुरपी','Walking shoes':'चलने के जूते','Umbrella':'छाता','Keys':'चाबियाँ','Small bag':'छोटा बैग','Steel spoon':'स्टील का चम्मच','Masala jar':'मसाले की बरनी','Steel tumbler':'स्टील का गिलास','Bed pillow':'बिस्तर का तकिया','Body lotion':'बॉडी लोशन','Bath bucket':'नहाने की बाल्टी','Cushion':'कुशन','Rice container':'चावल का डिब्बा','Tea kettle':'चाय की केतली','Clothes basket':'कपड़ों की टोकरी','Tawa':'तवा','Exercise book':'अभ्यास की कॉपी','Wall clock':'दीवार की घड़ी','Pencil':'पेंसिल','Ruler':'स्केल',
    'Wake up':'उठना','Brush teeth':'दाँत साफ करना','Wash face':'चेहरा धोना','Have tea':'चाय पीना','Have breakfast':'नाश्ता करना','Take medicine':'दवा लेना','Take a bath':'नहाना','Get dressed':'कपड़े पहनना','Comb hair':'बालों में कंघी करना','Go outside':'बाहर जाना','Notice the reminder':'रिमाइंडर देखना','Drink water':'पानी पीना','Sit and rest':'बैठकर आराम करना','Mark it as done':'पूरा हुआ चिन्हित करना','Have dinner':'रात का खाना खाना','Take evening medicine':'शाम की दवा लेना','Read a little':'थोड़ा पढ़ना','Wash up':'साफ-सफाई करना','Go to bed':'सोने जाना','Prepare tea':'चाय बनाना','Pour tea':'चाय डालना','Take a small snack':'थोड़ा नाश्ता लेना','Sit comfortably':'आराम से बैठना','Enjoy tea':'चाय का आनंद लेना','Get ready':'तैयार होना','Put on walking shoes':'चलने के जूते पहनना','Take the keys':'चाबियाँ लेना','Carry water':'पानी साथ लेना','Go for a walk':'टहलने जाना'
  });
  Object.assign(G['bn-IN'],{
    'Round':'রাউন্ড','Level':'স্তর','Score':'স্কোর','Misses':'ভুল','Mistakes':'ভুল','Question':'প্রশ্ন','Correct':'সঠিক','Step':'ধাপ','Game complete. Moving to the next game.':'খেলা শেষ। এবার পরের খেলায় যাই।','Next round.':'পরের রাউন্ড।','Next one.':'পরেরটি।','Next pattern.':'পরের প্যাটার্ন।','Look carefully…':'মন দিয়ে দেখুন…','Get ready…':'প্রস্তুত হন…','Your turn':'এবার আপনার পালা','Correct!':'সঠিক!','Incorrect':'ভুল','Not quite.':'পুরোপুরি ঠিক নয়।','Memory':'স্মৃতি','Attention':'মনোযোগ','Pattern Recognition':'প্যাটার্ন চিনুন','Object Recognition':'বস্তু চিনুন','Daily Routine Recall':'দৈনিক রুটিন মনে রাখা','MEMORY + ATTENTION':'স্মৃতি + মনোযোগ','ATTENTION + DAILY-LIFE RECOGNITION':'মনোযোগ + দৈনন্দিন জীবন চিনুন','DAILY-LIFE RECOGNITION':'দৈনন্দিন জীবন চিনুন','PATTERN RECOGNITION':'প্যাটার্ন চিনুন','OBJECT RECOGNITION + ATTENTION':'বস্তু চিনুন + মনোযোগ',
    'Kitchen':'রান্নাঘর','Study Table':'পড়ার টেবিল','Bedroom':'শোবার ঘর','Bathroom':'বাথরুম','Dining Area':'খাওয়ার জায়গা','Living Room':'বসার ঘর','Cleaning':'পরিষ্কার করা','Medicine Routine':'ওষুধের রুটিন','Morning Routine':'সকালের রুটিন','Cooking':'রান্না','Reading':'পড়া','Clothing':'পোশাক','Grocery Shopping':'বাজার করা','Garden':'বাগান','Going Outside':'বাইরে যাওয়া','Other place':'অন্য জায়গা',
    'Steel plate':'স্টিলের থালা','Cooking spoon':'রান্নার চামচ','Masala box':'মশলার বাক্স','Tea cup':'চায়ের কাপ','Soap':'সাবান','Toothbrush':'টুথব্রাশ','Bath towel':'গোসলের তোয়ালে','Comb':'চিরুনি','Notebook':'খাতা','Pen':'কলম','Reading glasses':'পড়ার চশমা','Calendar':'ক্যালেন্ডার','Pillow':'বালিশ','Bedsheet':'বিছানার চাদর','Shawl':'শাল','Alarm clock':'অ্যালার্ম ঘড়ি','Sofa cushion':'সোফার কুশন','Newspaper':'খবরের কাগজ','Remote control':'রিমোট','Table lamp':'টেবিল ল্যাম্প','Dinner plate':'খাওয়ার থালা','Serving bowl':'পরিবেশনের বাটি','Water glass':'জলের গ্লাস','Table mat':'টেবিল ম্যাট','Broom':'ঝাড়ু','Dustpan':'ডাস্টপ্যান','Cleaning cloth':'পরিষ্কারের কাপড়','Mop':'মপ','Medicine box':'ওষুধের বাক্স','Pill organizer':'ওষুধ রাখার বাক্স','Reminder card':'রিমাইন্ডার কার্ড','Face towel':'মুখ মোছার তোয়ালে','Cooking pot':'রান্নার হাঁড়ি','Spatula':'খুন্তি','Ladle':'হাতা','Cutting board':'কাটিং বোর্ড','Story book':'গল্পের বই','Bookmark':'বুকমার্ক','Shirt':'জামা','Socks':'মোজা','Clothes hanger':'কাপড়ের হ্যাঙ্গার','Shopping bag':'বাজারের ব্যাগ','Rice packet':'চালের প্যাকেট','Vegetable basket':'সবজির ঝুড়ি','Milk packet':'দুধের প্যাকেট','Plant pot':'গাছের টব','Watering can':'জল দেওয়ার পাত্র','Garden gloves':'বাগানের দস্তানা','Small trowel':'ছোট কোদাল','Walking shoes':'হাঁটার জুতো','Umbrella':'ছাতা','Keys':'চাবি','Small bag':'ছোট ব্যাগ','Steel spoon':'স্টিলের চামচ','Masala jar':'মশলার বয়াম','Steel tumbler':'স্টিলের গ্লাস','Bed pillow':'বিছানার বালিশ','Body lotion':'বডি লোশন','Bath bucket':'গোসলের বালতি','Cushion':'কুশন','Rice container':'চালের পাত্র','Tea kettle':'চায়ের কেটলি','Clothes basket':'কাপড়ের ঝুড়ি','Tawa':'তাওয়া','Exercise book':'অনুশীলনের খাতা','Wall clock':'দেয়াল ঘড়ি','Pencil':'পেন্সিল','Ruler':'স্কেল',
    'Wake up':'ঘুম থেকে ওঠা','Brush teeth':'দাঁত মাজা','Wash face':'মুখ ধোয়া','Have tea':'চা খাওয়া','Have breakfast':'সকালের নাস্তা করা','Take medicine':'ওষুধ খাওয়া','Take a bath':'গোসল করা','Get dressed':'কাপড় পরা','Comb hair':'চুল আঁচড়ানো','Go outside':'বাইরে যাওয়া','Notice the reminder':'রিমাইন্ডার দেখা','Drink water':'জল খাওয়া','Sit and rest':'বসে বিশ্রাম নেওয়া','Mark it as done':'সম্পন্ন হিসেবে চিহ্নিত করা','Have dinner':'রাতের খাবার খাওয়া','Take evening medicine':'সন্ধ্যার ওষুধ খাওয়া','Read a little':'একটু পড়া','Wash up':'পরিষ্কার হওয়া','Go to bed':'ঘুমাতে যাওয়া','Prepare tea':'চা তৈরি করা','Pour tea':'চা ঢালা','Take a small snack':'অল্প নাস্তা নেওয়া','Sit comfortably':'আরামে বসা','Enjoy tea':'চা উপভোগ করা','Get ready':'প্রস্তুত হওয়া','Put on walking shoes':'হাঁটার জুতো পরা','Take the keys':'চাবি নেওয়া','Carry water':'জল সঙ্গে নেওয়া','Go for a walk':'হাঁটতে যাওয়া'
  });
  Object.assign(G['as-IN'],{
    'Round':'ৰাউণ্ড','Level':'স্তৰ','Score':'স্ক’ৰ','Misses':'ভুল','Mistakes':'ভুল','Question':'প্ৰশ্ন','Correct':'শুদ্ধ','Step':'খোজ','Game complete. Moving to the next game.':'খেল সম্পূৰ্ণ। এতিয়া পৰৱৰ্তী খেললৈ যাওঁ।','Next round.':'পৰৱৰ্তী ৰাউণ্ড।','Next one.':'পৰৱৰ্তীটো।','Next pattern.':'পৰৱৰ্তী পেটাৰ্ন।','Look carefully…':'মন দি চাওক…','Get ready…':'প্ৰস্তুত হওক…','Your turn':'এতিয়া আপোনাৰ পাল','Correct!':'শুদ্ধ!','Incorrect':'ভুল','Not quite.':'সম্পূৰ্ণ শুদ্ধ নহয়।','Memory':'স্মৃতি','Attention':'মনোযোগ','Pattern Recognition':'পেটাৰ্ন চিনাক্তকৰণ','Object Recognition':'বস্তু চিনাক্তকৰণ','Daily Routine Recall':'দৈনিক কামৰ ক্ৰম মনত ৰখা','MEMORY + ATTENTION':'স্মৃতি + মনোযোগ','ATTENTION + DAILY-LIFE RECOGNITION':'মনোযোগ + দৈনন্দিন জীৱন চিনাক্তকৰণ','DAILY-LIFE RECOGNITION':'দৈনন্দিন জীৱন চিনাক্তকৰণ','PATTERN RECOGNITION':'পেটাৰ্ন চিনাক্তকৰণ','OBJECT RECOGNITION + ATTENTION':'বস্তু চিনাক্তকৰণ + মনোযোগ',
    'Kitchen':'ৰান্ধনীঘৰ','Study Table':'পঢ়াৰ মেজ','Bedroom':'শোৱা কোঠা','Bathroom':'বাথৰুম','Dining Area':'খোৱাৰ ঠাই','Living Room':'বহা কোঠা','Cleaning':'পৰিষ্কাৰ কৰা','Medicine Routine':'ঔষধৰ ৰুটিন','Morning Routine':'পুৱাৰ ৰুটিন','Cooking':'ৰন্ধা','Reading':'পঢ়া','Clothing':'কাপোৰ','Grocery Shopping':'বজাৰ কৰা','Garden':'বাগিচা','Going Outside':'বাহিৰলৈ যোৱা','Other place':'আন ঠাই',
    'Steel plate':'ষ্টীলৰ কাঁহী','Cooking spoon':'ৰন্ধাৰ চামুচ','Masala box':'মছলাৰ বাকচ','Tea cup':'চাহৰ কাপ','Soap':'চাবোন','Toothbrush':'দাঁত মাজা ব্ৰাছ','Bath towel':'গা ধোৱাৰ টাৱেল','Comb':'ফণী','Notebook':'বহী','Pen':'কলম','Reading glasses':'পঢ়াৰ চশমা','Calendar':'কেলেণ্ডাৰ','Pillow':'আঠুৱা','Bedsheet':'বিছনাৰ চাদৰ','Shawl':'শ্বাল','Alarm clock':'এলাৰ্ম ঘড়ী','Sofa cushion':'ছোফাৰ কুশ্বন','Newspaper':'বাতৰি কাকত','Remote control':'ৰিমোট','Table lamp':'টেবুল লেম্প','Dinner plate':'খোৱাৰ কাঁহী','Serving bowl':'পৰিবেশনৰ বাতি','Water glass':'পানীৰ গিলাচ','Table mat':'টেবুল মেট','Broom':'সাৰু','Dustpan':'আৱৰ্জনা তোলাৰ পাত্ৰ','Cleaning cloth':'পৰিষ্কাৰৰ কাপোৰ','Mop':'মপ','Medicine box':'ঔষধৰ বাকচ','Pill organizer':'ঔষধ ৰখা বাকচ','Reminder card':'সোঁৱৰনী কাৰ্ড','Face towel':'মুখ মচা টাৱেল','Cooking pot':'ৰন্ধাৰ পাত্ৰ','Spatula':'খুন্তি','Ladle':'হাতা','Cutting board':'কটিং ব’ৰ্ড','Story book':'গল্পৰ কিতাপ','Bookmark':'বুকমাৰ্ক','Shirt':'চাৰ্ট','Socks':'মোজা','Clothes hanger':'কাপোৰৰ হেংগাৰ','Shopping bag':'বজাৰৰ বেগ','Rice packet':'চাউলৰ পেকেট','Vegetable basket':'শাক-পাচলিৰ টোপোলা','Milk packet':'গাখীৰৰ পেকেট','Plant pot':'গছৰ টাব','Watering can':'পানী দিয়া পাত্ৰ','Garden gloves':'বাগিচাৰ হাতমোজা','Small trowel':'সৰু খুৰপি','Walking shoes':'খোজ কঢ়াৰ জোতা','Umbrella':'ছাতি','Keys':'চাবি','Small bag':'সৰু বেগ','Steel spoon':'ষ্টীলৰ চামুচ','Masala jar':'মছলাৰ বয়াম','Steel tumbler':'ষ্টীলৰ গিলাচ','Bed pillow':'বিছনাৰ আঠুৱা','Body lotion':'বডি লোচন','Bath bucket':'গা ধোৱাৰ বাল্টি','Cushion':'কুশ্বন','Rice container':'চাউলৰ পাত্ৰ','Tea kettle':'চাহৰ কেটলি','Clothes basket':'কাপোৰৰ টোপোলা','Tawa':'তোৱা','Exercise book':'অনুশীলনৰ বহী','Wall clock':'বেৰৰ ঘড়ী','Pencil':'পেঞ্চিল','Ruler':'স্কেল',
    'Wake up':'শুই উঠা','Brush teeth':'দাঁত মাজা','Wash face':'মুখ ধোৱা','Have tea':'চাহ খোৱা','Have breakfast':'জলপান খোৱা','Take medicine':'ঔষধ খোৱা','Take a bath':'গা ধোৱা','Get dressed':'কাপোৰ পিন্ধা','Comb hair':'চুলি ফণোৱা','Go outside':'বাহিৰলৈ যোৱা','Notice the reminder':'সোঁৱৰনীটো চোৱা','Drink water':'পানী খোৱা','Sit and rest':'বহি জিৰণি লোৱা','Mark it as done':'সম্পূৰ্ণ বুলি চিহ্নিত কৰা','Have dinner':'ৰাতিৰ আহাৰ খোৱা','Take evening medicine':'সন্ধিয়াৰ ঔষধ খোৱা','Read a little':'অলপ পঢ়া','Wash up':'পৰিষ্কাৰ হোৱা','Go to bed':'শুবলৈ যোৱা','Prepare tea':'চাহ বনোৱা','Pour tea':'চাহ ঢলা','Take a small snack':'অলপ জলপান লোৱা','Sit comfortably':'আৰামেৰে বহা','Enjoy tea':'চাহ উপভোগ কৰা','Get ready':'প্ৰস্তুত হোৱা','Put on walking shoes':'খোজ কঢ়াৰ জোতা পিন্ধা','Take the keys':'চাবি লোৱা','Carry water':'পানী লগত লোৱা','Go for a walk':'ফুৰিবলৈ যোৱা'  });
  Object.assign(G['lus-IN'],{'Round':'Round','Level':'Level','Score':'Score','Correct':'Correct','Incorrect':'Incorrect','Memory':'Memory','Attention':'Attention','Pattern Recognition':'Pattern Recognition','Start':'Sdang','Play':'Inkhel','Thank you':'Ka lawm e','How are you?':'I dam em?','Hello':'Chibai','Good morning':'Zingṭha'});
  Object.assign(G['kha-IN'],{'Round':'Round','Level':'Level','Score':'Score','Correct':'Correct','Incorrect':'Incorrect','Memory':'Memory','Attention':'Attention','Pattern Recognition':'Pattern Recognition','Start':'Sdang','Play':'Lĕhkai','Thank you':'Khublei','How are you?':'Kumno phi long?','Hello':'Khublei'});
  Object.assign(G['mni-IN'],{'Round':'Round','Level':'Level','Score':'Score','Correct':'Correct','Incorrect':'Incorrect','Memory':'Memory','Attention':'Attention','Pattern Recognition':'Pattern Recognition','Hello':'ꯈꯨꯔꯨꯝꯖꯔꯤ','How are you?':'ꯀꯝꯗꯧꯕꯤꯔꯤ?','Thank you':'ꯊꯥꯒꯠꯆꯔꯤ'});
  Object.assign(G['njz-IN'],{'Round':'Round','Level':'Level','Score':'Score','Correct':'Correct','Incorrect':'Incorrect','Memory':'Memory','Attention':'Attention','Pattern Recognition':'Pattern Recognition','Hello':'Bule','How are you?':'No hogub rido?','Thank you':'Payalincho!','Good morning':'Albo arkumch'});
  const PH={
    'hi-IN':[[/Round (\d+) \/ (\d+)/,'राउंड $1 / $2'],[/Level (\d+)/,'स्तर $1'],[/Score (\d+)/,'स्कोर $1'],[/Misses (\d+) \/ 3/,'गलतियाँ $1 / 3'],[/Mistakes (\d+) \/ 3/,'गलतियाँ $1 / 3'],[/Question (\d+) \/ (\d+)/,'सवाल $1 / $2'],[/Step (\d+) of (\d+)/,'कदम $1 में से $2'],[/Watch (\d+) of (\d+)/,'$1 में से $2 देखें'],[/(\d+) of (\d+) remembered/,'$1 में से $2 याद'],[/(\d+) of (\d+) sorted/,'$1 में से $2 छांटे गए'],[/(\d+) of (\d+)/,'$1 में से $2'],[/Complete!/,'पूरा!']],
    'bn-IN':[[/Round (\d+) \/ (\d+)/,'রাউন্ড $1 / $2'],[/Level (\d+)/,'স্তর $1'],[/Score (\d+)/,'স্কোর $1'],[/Misses (\d+) \/ 3/,'ভুল $1 / ৩'],[/Mistakes (\d+) \/ 3/,'ভুল $1 / ৩'],[/Question (\d+) \/ (\d+)/,'প্রশ্ন $1 / $2'],[/Step (\d+) of (\d+)/,'ধাপ $1 / $2'],[/Watch (\d+) of (\d+)/,'$1 / $2 দেখুন'],[/(\d+) of (\d+) remembered/,'$1 / $2 মনে আছে'],[/(\d+) of (\d+) sorted/,'$1 / $2 সাজানো হয়েছে'],[/(\d+) of (\d+)/,'$1 / $2'],[/Complete!/,'সম্পূর্ণ!']],
    'as-IN':[[/Round (\d+) \/ (\d+)/,'ৰাউণ্ড $1 / $2'],[/Level (\d+)/,'স্তৰ $1'],[/Score (\d+)/,'স্ক’ৰ $1'],[/Misses (\d+) \/ 3/,'ভুল $1 / ৩'],[/Mistakes (\d+) \/ 3/,'ভুল $1 / ৩'],[/Question (\d+) \/ (\d+)/,'প্ৰশ্ন $1 / $2'],[/Step (\d+) of (\d+)/,'খোজ $1 / $2'],[/Watch (\d+) of (\d+)/,'$1 / $2 চাওক'],[/(\d+) of (\d+) remembered/,'$1 / $2 মনত আছে'],[/(\d+) of (\d+) sorted/,'$1 / $2 ভাগ কৰা হৈছে'],[/(\d+) of (\d+)/,'$1 / $2'],[/Complete!/,'সম্পূৰ্ণ!']]
  };
  let locale=localStorage.getItem(KEY)||'en-IN';if(!LANGS[locale])locale='en-IN';
  const originals=new WeakMap(),attrs=new WeakMap();const text=()=>T[locale];
  function esc(s){return String(s).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));}
  function translateValue(value){if(value==null)return value;const raw=String(value);if(locale==='en-IN')return raw;const d=G[locale]||EN;if(d[raw])return d[raw];for(const [re,out] of (PH[locale]||[]))if(re.test(raw))return raw.replace(re,out);let out=raw;Object.keys(d).sort((a,b)=>b.length-a.length).forEach(k=>{if(k&&out.includes(k))out=out.split(k).join(d[k])});return out}
  function translateDom(root=document){const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let n;while((n=walker.nextNode())){if(!n.parentElement||['SCRIPT','STYLE'].includes(n.parentElement.tagName))continue;if(!originals.has(n))originals.set(n,n.nodeValue);n.nodeValue=translateValue(originals.get(n));}root.querySelectorAll?.('[aria-label],[title],[placeholder]').forEach(el=>{let store=attrs.get(el);if(!store){store={};attrs.set(el,store)}['aria-label','title','placeholder'].forEach(a=>{if(el.hasAttribute(a)){if(store[a]===undefined)store[a]=el.getAttribute(a);el.setAttribute(a,translateValue(store[a]))}})})}
  function updateVoiceLanguage(){window.CCNERLanguage={locale,language:LANGS[locale].name,nativeName:LANGS[locale].native,t:text,langs:LANGS,translate:translateValue};window.CCNERVoiceLocale=locale;try{const voices=window.speechSynthesis?.getVoices?.()||[];window.CCNERPreferredVoice=voices.find(v=>String(v.lang).toLowerCase().startsWith(locale.slice(0,2).toLowerCase()))||null}catch(_){}}
  function patchSpeech(){if(typeof window.say==='function'&&!window.say.__ccnerLocalized){const base=window.say;const wrapped=function(message,mood='happy',label=mood,opts={}){return base(translateValue(message),mood,label,opts)};wrapped.__ccnerLocalized=true;window.say=wrapped}if(typeof window.speak==='function'&&!window.speak.__ccnerLocalized){const base=window.speak;const wrapped=function(message,...args){return base(translateValue(message),...args)};wrapped.__ccnerLocalized=true;window.speak=wrapped}}
  function patchRecognition(){const Base=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Base||Base.__ccnerWrapped)return;const Wrapped=function(){const r=new Base();try{Object.defineProperty(r,'lang',{configurable:true,get:()=>locale,set:()=>{}})}catch(_){try{r.lang=locale}catch(__){}}return r};Wrapped.prototype=Base.prototype;Wrapped.__ccnerWrapped=true;window.SpeechRecognition=Wrapped;window.webkitSpeechRecognition=Wrapped}
  function apply(){document.documentElement.lang=locale;const t=text();const map={pageTitle:t.title,voiceHint:t.ready,chatInput:t.placeholder,todayStatus:t.activity};Object.entries(map).forEach(([id,val])=>{const e=document.getElementById(id);if(e&&id==='chatInput')e.placeholder=val;else if(e)e.textContent=val});const subtitle=document.querySelector('.subtitle');if(subtitle)subtitle.textContent=t.subtitle;const buttons=[...document.querySelectorAll('.quick-actions button')];if(buttons[0])buttons[0].textContent=t.start;if(buttons[1])buttons[1].textContent=t.talk;if(buttons[2])buttons[2].textContent=t.reminders;if(buttons[3])buttons[3].textContent=t.progress;const vb=document.querySelector('.voice-banner');if(vb){const strong=vb.querySelector('strong'),p=vb.querySelector('p');if(strong)strong.textContent=t.hands;if(p)p.textContent=t.handsText}const send=document.getElementById('sendButton');if(send)send.textContent=t.send;const labels=document.querySelectorAll('.section-label .eyebrow');if(labels[0])labels[0].textContent=t.today;const routine=document.querySelector('.section-label h2');if(routine)routine.textContent=t.routine;const info=document.querySelectorAll('.info-grid article');if(info[0]?.querySelector('span'))info[0].querySelector('span').textContent=t.activity;if(info[1]?.querySelector('span'))info[1].querySelector('span').textContent=t.games;if(info[2]?.querySelector('span'))info[2].querySelector('span').textContent=t.focus;const strip=document.querySelector('.home-strip strong');if(strip)strip.textContent=t.noPressure;const safety=document.querySelector('.phase4-safety');if(safety)safety.textContent=t.safety;const resultEyebrow=document.querySelector('#resultsView .result-hero .eyebrow');if(resultEyebrow)resultEyebrow.textContent=t.session;const perf=document.querySelector('#resultsView .results-card .eyebrow');if(perf)perf.textContent=t.performance;const heading=document.querySelector('#resultsView .results-card h3');if(heading)heading.textContent=t.todaysGames;const again=document.getElementById('playAgain');if(again)again.textContent=t.playAgain;const home=document.getElementById('backHome');if(home)home.textContent=t.home;translateDom(document);updateVoiceLanguage();patchSpeech();patchRecognition()}
  function installLanguageCard(){}
  function highlight(){document.querySelectorAll('[data-lang]').forEach(b=>b.classList.toggle('selected',b.dataset.lang===locale))}
  function setLanguage(next){if(!LANGS[next])return;locale=next;localStorage.setItem(KEY,locale);apply();highlight();const saved=document.getElementById('languageSaved');if(saved)saved.textContent=`✓ ${text().saved} · ${LANGS[next].native}`;window.dispatchEvent(new CustomEvent('ccner:language-change',{detail:{locale}}))}
  const observer=new MutationObserver(ms=>ms.forEach(m=>{if(m.type==='childList')m.addedNodes.forEach(n=>{if(n.nodeType===1)translateDom(n)});else if(m.type==='characterData'){if(!originals.has(m.target))originals.set(m.target,m.target.nodeValue);m.target.nodeValue=translateValue(originals.get(m.target))}}));
  function boot(){if(!document.body)return;observer.observe(document.body,{subtree:true,childList:true,characterData:true});installLanguageCard();apply();setTimeout(()=>{translateDom(document);patchSpeech();patchRecognition()},300)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
  setInterval(()=>{installLanguageCard();patchSpeech();patchRecognition()},1000);
  window.setLocale = setLanguage;
})();
