/* Cognitive Care NER — Phase 7
 * Privacy, local-data controls and secure export layer.
 * No diagnosis is inferred. Cloud security remains governed by Supabase auth/RLS.
 */
(() => {
  'use strict';
  const KEY='ccner-p7-privacy';
  const HISTORY='ccner-history';
  const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch(_){return f}};
  const write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));return true}catch(_){return false}};
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const state=Object.assign({privacyAcknowledged:false,analyticsConsent:false,notificationsConsent:false,lastExport:null},read(KEY,{}));
  const audit=(action,detail='')=>window.CognitiveCareProduction?.recordSafetyEvent?.(action,detail);
  function toast(msg){const old=document.querySelector('.p7-toast');old?.remove();const e=document.createElement('div');e.className='p7-toast';e.textContent=msg;document.body.appendChild(e);setTimeout(()=>e.remove(),2500)}
  function save(){write(KEY,state);window.CognitiveCareProduction?.setConsent?.('analytics',state.analyticsConsent);window.CognitiveCareProduction?.setConsent?.('notifications',state.notificationsConsent)}
  function localSummary(){const h=read(HISTORY,[]);return {sessions:Array.isArray(h)?h.length:0,localStorageBytes:JSON.stringify(localStorage).length}}
  function exportData(){const payload={exportedAt:new Date().toISOString(),purpose:'Cognitive training data portability',notice:'Training performance only. Not a diagnosis or clinical assessment.',history:read(HISTORY,[]),reminders:read('ccner-reminders',read('ccner-p1-reminders',[])),tasks:read('ccner-tasks',read('ccner-p1-tasks',[])),privacy:{analyticsConsent:!!state.analyticsConsent,notificationsConsent:!!state.notificationsConsent},audit:window.CognitiveCareProduction?.exportAudit?JSON.parse(window.CognitiveCareProduction.exportAudit()):[]};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='cognitive-care-ner-data.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);state.lastExport=new Date().toISOString();save();audit('privacy_export','local data export');toast('Your local data export has been prepared.')}
  function clearLocal(){if(!confirm('Delete local training history, reminders, tasks and privacy data from this device? Cloud data is not deleted by this action.'))return;['ccner-history','ccner-reminders','ccner-p1-reminders','ccner-tasks','ccner-p1-tasks','ccner-p6-sync-queue','ccner-p7-privacy','ccner_phase4'].forEach(k=>localStorage.removeItem(k));audit('local_data_deleted','device-local records');location.reload()}
  function render(){let panel=document.querySelector('.p7-panel');if(!panel){const home=document.querySelector('#homeView');if(!home)return;panel=document.createElement('section');panel.className='p7-panel';home.querySelector('.p6-panel')?.insertAdjacentElement('afterend',panel)||home.appendChild(panel)}const s=localSummary();panel.innerHTML='<div class="p7-row"><div><div class="p7-title">Privacy & data controls</div><p class="p7-sub">You control what stays on this device and what is used for optional analytics/notifications.</p></div><span class="p7-pill">🔒 Privacy controls</span></div><div class="p7-grid"><article class="p7-card"><span>Local training sessions</span><strong>'+s.sessions+'</strong></article><article class="p7-card"><span>Analytics consent</span><strong>'+(state.analyticsConsent?'Enabled':'Off')+'</strong></article><article class="p7-card"><span>Notifications consent</span><strong>'+(state.notificationsConsent?'Enabled':'Off')+'</strong></article><article class="p7-card"><span>Last export</span><strong>'+(state.lastExport?new Date(state.lastExport).toLocaleDateString():'Never')+'</strong></article></div><div class="p7-actions"><button class="p7-btn primary" id="p7Export" type="button">Export my data</button><button class="p7-btn" id="p7Consent" type="button">Manage consent</button><button class="p7-btn danger" id="p7Delete" type="button">Delete local data</button></div><div class="p7-lock"><strong>Security note:</strong> this browser layer does not expose service-role credentials. Cloud access uses the public client configuration and should be protected server-side with Supabase authentication and Row Level Security.</div><p class="p7-note">Deleting local data removes only this device\'s records. It does not claim to delete cloud records; cloud deletion requires the authenticated backend policy.</p>';document.querySelector('#p7Export').onclick=exportData;document.querySelector('#p7Delete').onclick=clearLocal;document.querySelector('#p7Consent').onclick=showConsent}
  function showConsent(){const old=document.querySelector('.p7-modal');old?.remove();const m=document.createElement('div');m.className='p7-modal';m.innerHTML='<section class="p7-sheet"><h2>Privacy choices</h2><p class="p7-sub">Optional controls for this demo.</p><label><input id="p7A" type="checkbox" '+(state.analyticsConsent?'checked':'')+'> Allow analytics/training trend aggregation</label><br><br><label><input id="p7N" type="checkbox" '+(state.notificationsConsent?'checked':'')+'> Allow reminder/notification features</label><div class="p7-actions"><button class="p7-btn primary" id="p7Save" type="button">Save choices</button><button class="p7-btn" id="p7Close" type="button">Cancel</button></div></section>';document.body.appendChild(m);m.querySelector('#p7Close').onclick=()=>m.remove();m.querySelector('#p7Save').onclick=()=>{state.analyticsConsent=m.querySelector('#p7A').checked;state.notificationsConsent=m.querySelector('#p7N').checked;state.privacyAcknowledged=true;save();audit('privacy_consent_updated');m.remove();render();toast('Privacy choices saved.')}}
  window.CCNER_PHASE7={refresh:render,exportData,deleteLocalData:clearLocal,getPrivacy:()=>({...state})};
  setTimeout(render,50);
})();
