/* Cognitive Care NER — UI, reminder and focused-voice upgrade. */
(() => {
  'use strict';
  const REM='ccner-p1-reminders', TASK='ccner-p1-tasks', HIST='ccner-history';
  const read=(k,f)=>{try{const v=JSON.parse(localStorage.getItem(k)||'null');return v??f}catch(_){return f}};
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const isGame=()=>!document.querySelector('#gameView')?.hidden;
  function addToast(){if(document.getElementById('momoReminderToast'))return;const t=document.createElement('div');t.id='momoReminderToast';t.className='reminder-toast';t.setAttribute('role','status');t.innerHTML='<strong id="momoReminderTitle">Momo reminder</strong><p id="momoReminderBody">It is time for your reminder.</p><button id="momoReminderOpen" type="button">Open Reminders</button>';document.body.appendChild(t);t.querySelector('#momoReminderOpen').onclick=()=>{t.classList.remove('show');window.CCNERPhase1?.openPanel?.('reminders')};}
  function showReminder(r){addToast();const t=document.getElementById('momoReminderToast');document.getElementById('momoReminderTitle').textContent=`Momo says: ${r?.title||'Reminder'}`;document.getElementById('momoReminderBody').textContent=r?.kind==='medicine'?'Please take your medicine now.':r?.kind==='hydration'?'Please drink a little water now.':`Please remember: ${r?.title||'it is time for your reminder'}.`;t.classList.add('show');navigator.vibrate?.([250,120,250]);if(!isGame()&&window.say)window.say(document.getElementById('momoReminderBody').textContent,'encourage','reminder');setTimeout(()=>t.classList.remove('show'),12000);}
  function nextReminder(){const rows=read(REM,[]).filter(r=>r.active!==false&&r.enabled!==false&&r.time);if(!rows.length)return null;const now=new Date();return rows.map(r=>{const [h,m]=String(r.time).split(':').map(Number);const d=new Date(now);d.setHours(h,m,0,0);if(d<=now)d.setDate(d.getDate()+1);return {...r,_d:d}}).sort((a,b)=>a._d-b._d)[0]}
  function renderSmartHome(){let box=document.getElementById('smartHome');if(!box){box=document.createElement('section');box.id='smartHome';box.className='smart-home';const anchor=document.querySelector('#homeView .section-label');anchor?.parentNode?.insertBefore(box,anchor);if(!anchor)return}const history=read(HIST,[]),last=history.at(-1),week=history.slice(-7);const reminders=read(REM,[]).filter(r=>r.active!==false&&r.enabled!==false);const tasks=read(TASK,[]);const done=tasks.filter(t=>t.completed).length,pct=tasks.length?Math.round(done/tasks.length*100):0;const next=nextReminder();const bars=week.map(s=>{const score=Math.max(8,Math.min(100,Number(s.score||0)));const d=new Date(s.date);return `<div style="flex:1;min-width:0"><i style="height:${score*.72}px;display:block"></i><span>${d.toLocaleDateString([], {weekday:'narrow'})}</span></div>`}).join('');box.innerHTML=`<article class="smart-card"><h3>Today at a glance</h3><p>${last?`Last session · ${Math.round(last.score||0)}% score · ${Math.round((last.accuracy||0)*100)}% accuracy`:'Your first session is ready whenever you are.'}</p><div class="smart-chart">${bars||'<div style="width:100%;color:var(--muted);font-size:.78rem">Complete a session to see your weekly graph.</div>'}</div></article><article class="smart-card"><h3>Next reminder</h3><div class="reminder-next"><div class="reminder-icon">⏰</div><div><div class="smart-value" style="font-size:1.35rem">${next?esc(next.time):'—'}</div><div class="smart-meta">${next?esc(next.title):'No reminders scheduled'}</div></div></div><div class="notification-status" id="notificationStatus"><span class="dot"></span><span>Checking device alerts…</span></div></article><article class="smart-card"><h3>Daily routine</h3><div style="display:flex;gap:14px;align-items:center;margin-top:8px"><div class="task-ring" style="--pct:${pct}"><strong>${pct}%</strong></div><div><div class="smart-value" style="font-size:1.35rem">${done}/${tasks.length||0}</div><div class="smart-meta">tasks completed today</div></div></div></article><article class="smart-card"><h3>Support at a glance</h3><ul class="smart-list"><li><span>Active reminders</span><strong>${reminders.length}</strong></li><li><span>Training sessions</span><strong>${history.length}</strong></li><li><span>Companion</span><strong class="done">Momo is ready</strong></li></ul></article>`;refreshNotificationStatus()}
  async function refreshNotificationStatus(){const el=document.getElementById('notificationStatus');if(!el)return;const n=window.CCNERNotifications;if(!n){el.querySelector('span:last-child').textContent='Device alerts available in Android app';return}try{const s=await n.check();const ok=s?.display==='granted';el.classList.toggle('off',!ok);el.querySelector('span:last-child').textContent=ok?'Device alerts enabled':'Open Reminders to enable device alerts'}catch(_){el.classList.add('off');el.querySelector('span:last-child').textContent='Device alert permission not enabled'}}
  function addMomoNav(){const nav=document.querySelector('.bottom-nav');if(!nav||nav.querySelector('[data-nav-momo]'))return;const b=document.createElement('button');b.type='button';b.className='momo-nav-button';b.dataset.navMomo='true';b.setAttribute('aria-label','Talk to Momo');b.innerHTML='<span class="momo-nav-face">🐶</span><small>Talk to Momo</small>';nav.insertBefore(b,nav.children[Math.min(2,nav.children.length)]);b.onclick=()=>openTalk();}
  function ensureGameWakeButton(){if(!isGame()||document.getElementById('gameMomoWake'))return;const host=document.querySelector('#gameView .mini-companion');if(!host)return;const b=document.createElement('button');b.id='gameMomoWake';b.type='button';b.className='momo-talk-game-button';b.textContent='🐶 Talk to Momo';b.setAttribute('aria-label','Wake Momo for one voice command');b.onclick=()=>{window.__ccnerWakeMode=true;window.CCNERGameControls?.wakeVoice?.();b.textContent='🎙️ Say “Momo”';};host.appendChild(b)}
  function openTalk(){const existing=document.getElementById('momoTalkOverlay');if(existing){existing.remove();return}const o=document.createElement('section');o.id='momoTalkOverlay';o.className='overlay-panel';o.innerHTML='<div class="overlay-inner"><button class="close-button" type="button" aria-label="Close">×</button><div class="momo-talk-panel"><p class="eyebrow">MOMO COMPANION</p><h2>Talk to Momo</h2><div class="talk-orb">🐶</div><div id="momoTalkStatus" class="talk-status">Tap the button and speak naturally.</div><div class="momo-talk-actions"><button id="momoTalkStart" class="primary" type="button">🎙️ Start talking</button><button id="momoTalkStop" type="button">Stop listening</button></div><p class="p1-muted">During a game, Momo stays quiet unless you deliberately wake him. When awake, say “Momo” first, then your request.</p></div></div>';document.body.appendChild(o);o.querySelector('.close-button').onclick=()=>{window.__ccnerWakeMode=false;window.CCNERGameControls?.muteVoice?.();o.remove()};o.querySelector('#momoTalkStart').onclick=()=>{const status=o.querySelector('#momoTalkStatus');status.textContent='Listening… say “Momo” first, then your question.';window.__ccnerWakeMode=true;window.CCNERGameControls?.wakeVoice?.()};o.querySelector('#momoTalkStop').onclick=()=>{window.__ccnerWakeMode=false;window.CCNERGameControls?.muteVoice?.();o.querySelector('#momoTalkStatus').textContent='Voice paused.'};}
  function installFocusedVoice(){if(window.__ccnerVoiceUpgrade)return;const original=window.respond;if(typeof original!=='function')return;window.respond=function(raw){const text=String(raw||'').trim();if(isGame()){if(!window.__ccnerWakeMode)return;const m=text.match(/\bmomo\b[,:;.!?\s-]*(.*)$/i);if(!m)return;window.__ccnerWakeMode=false;window.CCNERGameControls?.muteVoice?.();const command=(m[1]||'').trim();return original(command||'I need help with this game.')}return original(text)};window.__ccnerVoiceUpgrade=true;}
  function silenceDuringGame(){if(isGame()&&!window.__ccnerWakeMode)window.CCNERGameControls?.muteVoice?.()}
  function wireReminderEvents(){document.addEventListener('submit',e=>{if(e.target?.id==='p1ReminderForm')setTimeout(()=>{window.CCNERNotifications?.syncAll?.();renderSmartHome()},250)});document.addEventListener('click',e=>{if(e.target.closest('[data-remove-reminder]'))setTimeout(()=>{window.CCNERNotifications?.syncAll?.();renderSmartHome()},250)});window.addEventListener('focus',()=>window.CCNERNotifications?.syncAll?.());window.addEventListener('ccner:reminder-fired',e=>showReminder(e.detail||{}));}
  function init(){addToast();addMomoNav();renderSmartHome();installFocusedVoice();wireReminderEvents();setInterval(()=>{addMomoNav();installFocusedVoice();ensureGameWakeButton();if(!isGame())renderSmartHome();silenceDuringGame()},5000);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,500));else setTimeout(init,500);
  window.CCNERUIUpgrade={openTalk,renderSmartHome,showReminder};
})();